#!/usr/bin/env bash
#
# Simple script for printing a colored line across the terminal window
#
# author: RilCritch

# Imports - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
. "${BASH_HOME}/ansi_escape_sequences"
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

terminalwidth=$(tput cols)

if [ -z "$1" ]; then
	character="─"
else
    if [[ "${#1}" -eq 1 ]]; then
        character="$1"
    else
        echo -e "${red}ERROR:${reset} This script only supports single character strings"
    fi
fi

for ((i = 1; i <= terminalwidth; i++)); do
	echo -n "$character"
done

echo
