#!/usr/bin/env bash
#
# Simple script for printing a colored line across the terminal window
#
# author: RilCritch

terminalwidth=$(tput cols)

if [ -z "$1" ]; then
  word="-"
else
  word="$1"
fi

if [ -z "$2" ]; then
  character="-"
else
  character="$2"
fi

for (( i=1 ; i<=$terminalwidth ; i++ ));
do
  echo -n "$character"
done

echo
