#!/usr/bin/env bash
#
# a basic script that prints a title with a specified string (default: terminal name)
# arguments: 1: string 2: color of sparky; 3: color of lineacross; 4: color of figlet;
# color options: black, red, green yellow, blue, magenta, cyan, white (add L to end for light variant)
# 
# author: RilCritch
# 
# dependcies: 
#             non-custom: figlet
#             custom:     sparky, linacross, clr, colors.sh    

# source /home/rc/scripts/lineacross
# source /home/rc/scripts/sparky
# source /home/rc/scripts/clr

# setting colors
title=""
sparkycolor=""
lineacrosscolor=""
figletcolor=""

if [ -z "$1" ];
then
  title=$TERM
else
  title=$1
fi

if [ -z "$2" ];
then
  sparkycolor="whiteL"
else
  sparkycolor=$2
fi

if [ -z "$3" ];
then
  lineacrosscolor="whiteL"
else
  lineacrosscolor=$3
fi

if [ -z "$4" ];
then
  figletcolor="white"
else
  figletcolor=$4
fi

# output
lineacross | clr $lineacrosscolor
sparky | clr $sparkycolor
lineacross | clr $lineacrosscolor

figlet -w $(tput cols) -c "${title}" | clr $figletcolor

lineacross | clr $lineacrosscolor
sparky | clr $sparkycolor
lineacross | clr $lineacrosscolor
