#!/usr/bin/env bash

# Some bash environment settings for scratchpads
# - These are necessary due to bash running non-interactively

# Environment Variables

# FZF
export FZF_DEFAULT_OPTS="--header-first \
--reverse --border-label-pos=2 -i \
--no-scrollbar --border --height=100% \
--pointer='' --marker='󰮺' \
--color='\
fg:black,fg+:-1,preview-fg:white,\
bg:-1,bg+:-1,preview-bg:-1,\
hl:cyan:dim,hl+:blue:underline,\
query:cyan,disabled:cyan:dim,\
prompt:cyan:dim,pointer:blue,marker:blue:dim,\
info:bright-white,spinner:yellow,\
border:white,separator:bright-black:dim,scrollbar:8:dim,\
header:cyan,label:blue:bold,preview-label:cyan'"

# Functions

pathadd() {
    if [ -d "$1" ] && [[ ":$PATH:" != *":$1:"* ]]; then
        export PATH="${PATH:+"$PATH:"}$1"
    fi
}
